name = "ntl-calculator"
main = "src/index.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "ntl-calculator-prod"

[env.staging]
name = "ntl-calculator-staging"

# Uncomment to configure custom domain
# [[env.production.routes]]
# pattern = "calculator.yourdomain.com/*"

# Configure limits
# [limits]
# cpu_ms = 50